# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raretet/Code/matrix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raretet/Code/matrix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raretet/Code/matrix/CMakeFiles /home/raretet/Code/matrix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raretet/Code/matrix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named measure_time

# Build rule for target.
measure_time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 measure_time
.PHONY : measure_time

# fast build rule for target.
measure_time/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/build
.PHONY : measure_time/fast

src/matrix.o: src/matrix.cpp.o
.PHONY : src/matrix.o

# target to build an object file
src/matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/matrix.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/src/matrix.cpp.o
.PHONY : src/matrix.cpp.o

src/matrix.i: src/matrix.cpp.i
.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/matrix.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/src/matrix.cpp.i
.PHONY : src/matrix.cpp.i

src/matrix.s: src/matrix.cpp.s
.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/matrix.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/src/matrix.cpp.s
.PHONY : src/matrix.cpp.s

src/matrix_multithread_handler.o: src/matrix_multithread_handler.cpp.o
.PHONY : src/matrix_multithread_handler.o

# target to build an object file
src/matrix_multithread_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/matrix_multithread_handler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/src/matrix_multithread_handler.cpp.o
.PHONY : src/matrix_multithread_handler.cpp.o

src/matrix_multithread_handler.i: src/matrix_multithread_handler.cpp.i
.PHONY : src/matrix_multithread_handler.i

# target to preprocess a source file
src/matrix_multithread_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/matrix_multithread_handler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/src/matrix_multithread_handler.cpp.i
.PHONY : src/matrix_multithread_handler.cpp.i

src/matrix_multithread_handler.s: src/matrix_multithread_handler.cpp.s
.PHONY : src/matrix_multithread_handler.s

# target to generate assembly for a file
src/matrix_multithread_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/matrix_multithread_handler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/src/matrix_multithread_handler.cpp.s
.PHONY : src/matrix_multithread_handler.cpp.s

src/test.o: src/test.cpp.o
.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

src/time_measuring.o: src/time_measuring.cpp.o
.PHONY : src/time_measuring.o

# target to build an object file
src/time_measuring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/src/time_measuring.cpp.o
.PHONY : src/time_measuring.cpp.o

src/time_measuring.i: src/time_measuring.cpp.i
.PHONY : src/time_measuring.i

# target to preprocess a source file
src/time_measuring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/src/time_measuring.cpp.i
.PHONY : src/time_measuring.cpp.i

src/time_measuring.s: src/time_measuring.cpp.s
.PHONY : src/time_measuring.s

# target to generate assembly for a file
src/time_measuring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/measure_time.dir/build.make CMakeFiles/measure_time.dir/src/time_measuring.cpp.s
.PHONY : src/time_measuring.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... measure_time"
	@echo "... run_tests"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/matrix_multithread_handler.o"
	@echo "... src/matrix_multithread_handler.i"
	@echo "... src/matrix_multithread_handler.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/time_measuring.o"
	@echo "... src/time_measuring.i"
	@echo "... src/time_measuring.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

